backend:
  name: git-gateway
  branch: main

media_folder: "FOTOS"
public_folder: "/FOTOS"

collections:
  - name: "agenda"
    label: "Agenda"
    folder: "conteudo/agenda"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Descrição", name: "description", widget: "text"}

  - name: "musicas"
    label: "Músicas"
    folder: "conteudo/Musicas"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Letra", name: "lyrics", widget: "markdown"}
